#run examples
./examples/tutorial/viennacl-info
./examples/tutorial/amg
./examples/tutorial/bisect
./examples/tutorial/custom-context
./examples/tutorial/fft
./examples/tutorial/libviennacl-tutorial
./examples/tutorial/matrix-free
./examples/tutorial/scheduler
./examples/tutorial/wrap-host-buffer
./examples/tutorial/bandwidth-reduction
./examples/tutorial/blas1
./examples/tutorial/custom-kernels
./examples/tutorial/iterative-custom
./examples/tutorial/nmf
#benchmark
./examples/benchmarks/dense_blas-bench-opencl
./examples/benchmarks/opencl-bench-opencl
#test
./tests/matrix_row_float-test-opencl
./tests/matrix_col_int-test-opencl
./tests/scalar-test-opencl
./tests/matrix_vector-test-opencl
./tests/nmf-test-opencl
./tests/fft_1d-test-opencl
./tests/matrix_product_double-test-opencl
./tests/tql-test-opencl
./tests/matrix_col_float-test-opencl
./tests/matrix_row_int-test-opencl
./tests/qr_method_func-test-opencl
./tests/matrix_vector_int-test-opencl
./tests/spmdm-test-opencl
./tests/matrix_row_double-test-opencl
./tests/external_linkage-opencl
./tests/global_variables-test-opencl
./tests/matrix_convert-test-opencl
./tests/structured-matrices-test-opencl
./tests/vector_convert-test-opencl
./tests/vector_multi_inner_prod-test-opencl
./tests/vector_float_double-test-opencl
./tests/scan-test-opencl
./tests/svd-test-opencl
./tests/sparse_prod-test-opencl
./tests/iterators-test-opencl
./tests/blas3_solve-test-opencl
./tests/qr_method-test-opencl
./tests/bisect-test-opencl
./tests/sparse-test-opencl
./tests/vector_uint-test-opencl
./tests/matrix_col_double-test-opencl
./tests/fft_2d-test-opencl
./tests/vector_int-test-opencl
./tests/matrix_product_float-test-opencl
./tests/self_assign-test-opencl